
export const LOAD_DEFAULT_STOCKS = 'stock/LOAD_DEFAULT_STOCKS';
export const LOAD_DEFAULT_STOCKS_REQUEST = 'stock/LOAD_DEFAULT_STOCKS_REQUEST';
export const LOAD_SEARCHED_STOCKS = 'stock/LOAD_SEARCHED_STOCKS';


