spring:
  application:
    name: stockanalytics-api
  profiles:
    active: local
    
server:
  port: 8000
    
---
spring:
  profiles: local
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: neo4j
      
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

